# Verwenden Sie das offizielle PostgreSQL-Base-Image
FROM postgres

# Umgebungsvariablen für die PostgreSQL-Konfiguration festlegen
ENV POSTGRES_USER myuser
ENV POSTGRES_PASSWORD mypassword
ENV POSTGRES_DB mydatabase

# Fügen Sie optional zusätzliche Anpassungen oder Skripte hinzu



# Port freigeben
EXPOSE 5432

# Startbefehl für den PostgreSQL-Server
CMD ["postgres"]

